[package]
name = "sinoptik"
version = "0.1.0"
edition = "2021"

[dependencies]
cached = { version = "0.30.0", features = ["async"] }
chrono = "0.4.19"
chrono-tz = "0.6.1"
color-eyre = "0.5.6"
csv = "1.1.6"
geocoding = "0.3.1"
image = "0.24.0"
reqwest = { version = "0.11.9", features = ["json"] }
rocket = { version = "0.5.0-rc.1", features = ["json"] }
