[package]
name = "sinoptik"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
color-eyre = "0.5.6"
geocoding = "0.3.1"
image = "0.24.0"
once_cell = "1.9.0"
reqwest = "0.11.9"
rocket = { version = "0.5.0-rc.1", features = ["json"] }
